<%@ Page Title="" Language="C#" MasterPageFile="~/User/user.master" AutoEventWireup="true"
    CodeFile="usertikbuk.aspx.cs" Inherits="User_Default" %>
    <asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
        <style type="text/css">
            .style1
            {
                width: 100%;
            }
        </style>
</asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    
    <table class="style1">
        <tr>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td>
                <asp:MultiView ID="MultiView1" runat="server" ActiveViewIndex="0">
                    <asp:View ID="View1" runat="server">
                    <table style="width: 100%; height: 198px;">
        <tr>
            <td colspan="2" style="text-align: center">
                <asp:Label ID="Label1" runat="server" Style="color: #000000" Text="TICKET BOOKING"></asp:Label>
            </td>
        </tr>
        <tr>
            <td style="height: 26px">
                <asp:Label ID="Label5" runat="server" Style="color: #000000" Text="EXPO NAME"></asp:Label>
            </td>
            <td style="height: 26px">
                <asp:DropDownList ID="ddlexpo" runat="server" CssClass="textbox"
                    onselectedindexchanged="ddlexpo_SelectedIndexChanged">
                </asp:DropDownList>
            </td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="Label3" runat="server" Style="color: #000000" Text="TICKET TYPE"></asp:Label>
            </td>
            <td>
                <asp:DropDownList ID="ddlticket" runat="server" CssClass="textbox" 
                    AutoPostBack="True" onselectedindexchanged="ddlticket_SelectedIndexChanged">
                </asp:DropDownList>
            </td>
        </tr>
                        <tr>
                            <td>
                                <asp:Label ID="Label6" runat="server" Style="color: #000000" Text="DATE"></asp:Label>
                            </td>
                            <td>
                                <asp:TextBox ID="date" runat="server" CssClass="textbox"></asp:TextBox>
                                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                                    ControlToValidate="date" ErrorMessage="enter date"></asp:RequiredFieldValidator>
                            </td>
                        </tr>
        <tr>
            <td>
                <asp:Label ID="Label4" runat="server" Style="color: #000000" Text="TICKET RATE"></asp:Label>
            </td>
            <td>
                <asp:TextBox ID="TextBox1" runat="server" CssClass="textbox"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" 
                    ControlToValidate="TextBox1" ErrorMessage="enter ticketdate"></asp:RequiredFieldValidator>
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                <asp:Button ID="Button1" runat="server" style="height:40px;width:120px; border-radius: 5px;
    background-color: sandybrown;" OnClick="Button1_Click" Text="BOOK HERE" />
                <asp:Button ID="Button2" runat="server" style="height:40px;width:120px; border-radius: 5px;
    background-color: sandybrown;" Text="View History" 
                    onclick="Button2_Click" CausesValidation="False" />
                <asp:Button ID="Button3" runat="server" style="height:40px;width:120px; border-radius: 5px;
    background-color: sandybrown;" Text="GET TICKETS" onclick="Button3_Click" 
                    CausesValidation="False" />
            </td>
        </tr>
    </table>


                    </asp:View>
                    <asp:View ID="View2" runat="server">
                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                            AutoGenerateDeleteButton="True" DataKeyNames="ticketid" 
                            onrowdeleting="GridView1_RowDeleting" BackColor="LightGoldenrodYellow" 
                            BorderColor="Tan" BorderWidth="1px" CellPadding="2" ForeColor="Black" 
                            GridLines="None">
                            <AlternatingRowStyle BackColor="PaleGoldenrod" />
                            <Columns>
                                <asp:BoundField DataField="expotitle" HeaderText="Expo Name" />
                                <asp:BoundField DataField="date" HeaderText="Booked Date" />
                                <asp:BoundField DataField="tickettype" HeaderText="Ticket Type" />
                                <asp:BoundField DataField="ticketrate" HeaderText="Ticket Rate" />
                            </Columns>
                            <FooterStyle BackColor="Tan" />
                            <HeaderStyle BackColor="Tan" Font-Bold="True" />
                            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" 
                                HorizontalAlign="Center" />
                            <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
                            <SortedAscendingCellStyle BackColor="#FAFAE7" />
                            <SortedAscendingHeaderStyle BackColor="#DAC09E" />
                            <SortedDescendingCellStyle BackColor="#E1DB9C" />
                            <SortedDescendingHeaderStyle BackColor="#C2A47B" />
                        </asp:GridView>
                        <asp:Button ID="Button4" runat="server" style="height:40px;width:120px; border-radius: 5px;
    background-color: sandybrown;" Text="BACK TO ORDER" onclick="Button4_Click" />
                    </asp:View>
                </asp:MultiView>
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
        </tr>
    </table>
    
</asp:Content>
