<%@ Page Title="" Language="C#" MasterPageFile="~/company/company.master" AutoEventWireup="true" CodeFile="viewexpoo.aspx.cs" Inherits="company_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <marquee direction="left" class="auto-style1"><asp:Label ID="Label10" runat="server" Text=""></asp:Label></marquee>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        DataKeyNames="expoId"  Width="646px" 
        AutoGenerateDeleteButton="True" onrowdeleting="GridView1_RowDeleting" 
    BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" 
    CellPadding="3" ForeColor="Black" GridLines="Vertical"  >
        <AlternatingRowStyle BackColor="#CCCCCC" />
    <Columns>
        <asp:BoundField DataField="expotitle" HeaderText="Expo Name" />
        <asp:BoundField DataField="expotype" HeaderText="Expo Type" />
        <asp:BoundField DataField="category" HeaderText="Category" />
        <asp:BoundField DataField="subcategory" HeaderText="Subcategory" />
        <asp:BoundField DataField="country" HeaderText="Country" />
        <asp:BoundField DataField="place" HeaderText="Place" />
        <asp:BoundField DataField="numberofbooth" HeaderText="No of booths" />
        <asp:BoundField DataField="image" HeaderText="Image" />
        <asp:BoundField DataField="startingdate" HeaderText="Starting Date" />
    </Columns>
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#808080" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#383838" />
</asp:GridView>
</asp:Content>

