<%@ Page Title="" Language="C#" MasterPageFile="~/company/company.master" AutoEventWireup="true" CodeFile="viewalloc.aspx.cs" Inherits="company_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            text-align: center;
            color: #FF0000;
        width: 397px;
    }
        .auto-style2 {
            font-size: x-large;
            text-align: center;
            position: relative;
            top: 82px;
            left: 239px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1 class="auto-style2">Allocation</h1>
       <p>&nbsp;</p> 
    <br />
    <br />
    <p><marquee direction="left" class="auto-style1"><asp:Label ID="Label10" runat="server" Text=""></asp:Label></marquee></p>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        DataKeyNames="allocationid" onrowcommand="GridView1_RowCommand" 
        AutoGenerateDeleteButton="True" onrowdeleting="GridView1_RowDeleting" 
    BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" 
    CellPadding="3" CellSpacing="1" GridLines="None">
        <Columns>
            <asp:BoundField DataField="expotitle" HeaderText="Expo Name" />
            <asp:BoundField DataField="startingdate" HeaderText="Expo Date" />
            <asp:BoundField DataField="country" HeaderText="Country" />
            <asp:BoundField DataField="place" HeaderText="Place" />
            <asp:BoundField DataField="mobilenumber" HeaderText="Mobile " />
            <asp:BoundField DataField="boothnumber" HeaderText="Boothnumber" />
            <asp:BoundField DataField="plans" HeaderText="Plan" />
            <asp:ButtonField CommandName="confirm" Text="Confirm" />
        </Columns>
        <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
        <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
        <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
        <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
        <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#594B9C" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#33276A" />
    </asp:GridView>
</asp:Content>

